config/routes.rb
Auth::Application.routes.draw do
  get "presents/index" => "presents#index"
  get "reserve" => "presents#reserve_present", :as => "reserve"
  get "presents/new"
  get "presents/manage" => "presents#manage", :as => "manage_presents"
  get "kirkko" => "pages#kirkko"

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "attend" => "users#attend", :as => "attend"
  root :to => "pages#index"
  
  resources :users do
    resources :guests
  end
  resources :sessions
  resources :presents

end

app/models/guest.rb
class Guest < ActiveRecord::Base
  belongs_to :user
end

app/models/present.rb
class Present < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :password_confirmation

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username
  validates_uniqueness_of :username

  has_many :presents
  has_many :guests

  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


  helper_method :current_user
  helper_method :check_login
  helper_method :check_admin

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def check_login
    if current_user == nil 
      redirect_to log_in_url
    end
  end

  def check_admin
    if current_user.admin != true
      redirect_to root_url
    end
  end

end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_filter :check_login
  def new 
    @guest = Guest.new
    @user  = User.find(params[:user_id])
  end

  def create
    user = User.find(params[:user_id])
    @guest = user.guests.build(params[:guest])
    if @guest.save
      redirect_to root_url
    else
      render "new"
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :check_login

  def index 
  end

  def kirkko
  end

  
end

app/controllers/presents_controller.rb
class PresentsController < ApplicationController
  before_filter :check_login

  def index
    @presents = Present.order("name").all
  end

  def new
    @present = Present.new
  end

  def create
    @present = Present.new(params[:present])
    if @present.save
      redirect_to manage_presents_path 
    else
      render "new"
    end
  end
  
  def edit 
    @present = Present.find(params[:id]) 
  end

  def destroy 
    @present = Present.find(params[:id])
    @present.destroy
    redirect_to manage_presents_path
  end

  def update 
    @present = Present.find(params[:id])
    if @present.update_attributes(params[:present])
      redirect_to presents_index_path
    end
  end

  def reserve_present
    value = !Present.find(params[:present]).reserved
    if value == true
      Present.update(params[:present], :reserved => value, :reserver => current_user.id)
    elsif Present.find(params[:present]).reserver == current_user.id
      Present.update(params[:present], :reserved => value, :reserver => nil)
    end
    redirect_to presents_index_url  
  end

  def manage
    check_admin
    @presents = Present.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create 
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password!"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :check_login
  
  def new
    @user = User.new
  end
  
  def index
    @users = User.order(:username)
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def create 
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def show
    @user = current_user
  end

  def attend
      @user = User.find(session[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/present_helper.rb
module PresentHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/guests/new.html.erb
<h1>Luo uusi vieras käyttäjälle <%= @user.username %></h1>

<%= form_for(@guest, url: user_guests_path) do |f| %>
  <fieldset id="guests">
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name, :autofocus => true %>
  </p>
  <p>
  </p>
  <p class="button"><%= f.submit "Luo" %></p>
</fieldset>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taru ja Ville 2012</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
  <div id="header">
    <%= image_tag("headerImage.jpg") %>
  <div id="user_nav">
    <% if current_user %>
      <%= link_to "Etusivu", root_path %>
      <%= link_to "Kirkko & juhlapaikka", "kirkko" %>
      <%= link_to "Lahjalista", presents_path %>
      <%= link_to "Ilmoittautuminen", "#" %>
      <%= link_to "Log out", log_out_path %>
    <% end %>
  </div>
</div>
<div id="content">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/pages/index.html.erb
Moro

app/views/pages/kirkko.html.erb
<h2>Juhlapaikka</h2>
<p>
Hääjuhlaa vietetään Kangasalla Tiihalassa <a href="http://www.ali-marttila.com">Ali-Marttilan juhlatalolla.</a> 
Siirtymiseen kirkolta juhlapaikkaan olemme varanneet noin tunnin verran, alkumalja nostetaan n klo 16.30. 
Olemme varanneet bussikuljetuksen kirkolta juhlapaikkaan, johon voit halutessasi osallistua. Tarkemmat tiedot
bussikyydistä saatte juhlapäivänä kirkko-ohjelmassa. Ilmaisethan halukkuutesi bussikyytiin ilmoittautumisen yhteydessä.
Ali-Marttilassa parkkitilaa on hyvin ja se on maksutonta.</p>

app/views/presents/_form.html.erb
<%= form_for @present do |f| %>
  <% if @present.errors.any? %>
  <div class="error_messages">
    <h2>Lomakkeen tiedoissa oli virheitä:</h2>
    <ul>
      <% for message in @present.errrors.full_messages %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<p>
<%= f.label :nimi %><br />
<%= f.text_field :name %>
</p>
<p>
<%= f.radio_button(:reserved, true) %>
<%= f.label(:reserved_true, "Varattu") %>
<%= f.radio_button(:reserved, false) %>
<%= f.label(:reserved_false, "Vapaa") %>
</p>
<p>
  <%= f.label :varaaja %><br />
  <%= f.text_field :reserver %>
</p>
<p class="button"><%= f.submit %></p>
<% end %>

app/views/presents/edit.html.erb
<h2>Lahjan muokkaus</h2>

<%= render 'form' %>

<%= link_to 'Palaa tallentamatta', manage_presents_path %> 

app/views/presents/index.html.erb
<% if current_user.admin == true %>
  <%= link_to image_tag('pencil_icon.png'), manage_presents_path, :class => 'manageImage' %>
<% end %>
<table id="presents_table">
  <thead>
    <th>Lahja</th>
    <th>Varattu</th>
    <th></th>
  </thead>
  <tbody>
  <% for present in @presents %>
    <tr>
      <td><%= present.name %></td>
      <td> 
    <% if present.reserved == true %>
      Varattu
    <% else %>
      Vapaa
    <% end %>
  </td> 
  <td>
    <% if present.reserved == false %>
      <%= link_to 'Varaa', reserve_path(:present => present.id) %>
    <% end %>
  <% if current_user.id == present.reserver %>
    <%= link_to  'Peruuta varaus', reserve_path(:present => present.id) %>
  <% end %>
</td>
    </tr>
<% end %>
  </tbody>
</table>

app/views/presents/manage.html.erb
<h2>Lahjojen hallinnointi</h2>

<ul id="manageFunctions">
  <li><%= link_to "Lisää uusi", new_present_path %></li>
  <li><%= link_to 'Palaa', presents_index_path, :class => "back_link" %></li>
</ul>

<table id="presents_table">
  <thead>
    <th>Lahja</th>
    <th>Varaaja</th>
    <th></th>
    <th />
  </thead>
  <tbody>
 
    <% for present in @presents %>
      <tr>

        <td> <%= present.name %> </td>
        <td>
          <% if present.reserver != nil %>
            <%= User.find(present.reserver).username %>
          <% end %> 
        </td>
      <td>
        <%= link_to "Muokkaa", edit_present_path(present) %> </td>
      <td>
        <%= link_to "Poista", present, :method => :delete %>
      </td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/presents/new.html.erb
<h1>Luo uusi lahja</h1>

<%= render 'form' %>
<%= link_to 'Palaa tallentamatta', manage_presents_path %> 

app/views/users/_user.html.erb
<h3><%= @user.username %></h3>

app/views/users/attend.html.erb
<h1>Ilmoittautuminen</h1>
<p>
Toivomme, että teette ilmoittautumisen näiden sivujen kautta 15.7.2012
mennessä.  Tarvittaessa saatte lisätietoa sulhaselta puhelinnumerosta 
040 7608 233.
</p>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is valid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
  <%= f.label :password %><br />
  <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation%>
  </p>
  <p class ="button"><%= f.submit%></p>
<% end%>

app/views/users/edit.html.erb
<%= render (@user) %>

app/views/users/index.html.erb
<h2>Vieraat</h2>

<% for user in @users %>
  <h3>  <%= user.username %> </h3>
  <table id="user_table">
    <thead>
      <th>Vieras</th>
      <th>Vahvistanut osallistumisensa</th>
    </thead>
    <tbody>
      <% for guest in user.guests %>
        <tr>
          <td>
            <%= guest.name %>
          </td>
          <td>
          </td>
        </tr>
       <% end %>
     </tbody>
   </table>
  <br />
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
  <%= f.label :password %><br />
  <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation%>
  </p>
  <p class ="button"><%= f.submit%></p>
<% end%>

app/views/users/show.html.erb
<p><%= @user.username %></p>
<% for guest in @user.guests %>
  <%= guest.name %>
<% end %>